environment:
  matrix:
    - PYTHON: "C:\\PYTHON27"
    - PYTHON: "C:\\PYTHON34"
    - PYTHON: "C:\\PYTHON35"
    - PYTHON: "C:\\PYTHON36"
install:
  - "%PYTHON%\\python.exe -m pip install -U pip"
  - "%PYTHON%\\python.exe -m pip install nose coverage codecov psutil pynput babel pillow pypiwin32"
build: off
test_script:
  - "%PYTHON%\\python.exe -m pip install ."
  - "%PYTHON%\\python.exe -m nose --with-coverage"
after_test:
  - "%PYTHON%\\Scripts\\codecov.exe"
