language: python
required: sudo
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
virtualenv:
    system_site_packages: true
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - sudo apt-get install python-tk
  - python -m pip install nose coverage codecov mock pynput
script:
  - python -m pip install .
  - rm -R ttkwidgets
  - python -m nose --with-coverage
after_success:
- codecov
