language: python
required: sudo
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - "export DISPLAY=:99.0"
  - sudo systemctl start xvfb
  - sleep 3
install:
  - sudo apt-get install python-tk python3-tk
  - python -m pip install nose coverage codecov psutil pynput babel
script:
  - python -m pip install .
  - python -m nose --with-coverage
after_success:
- codecov
